// ignore_for_file: public_member_api_docs, sort_constructors_first
class Hr {
  String name;
  String contact;
  String email;
  String autoGeneratedPassword;
  Hr({
    required this.name,
    required this.contact,
    required this.email,
    required this.autoGeneratedPassword,
  });
}

final List<Hr> hrList = [
  Hr(
      name: 'Mike Dean',
      contact: '645875957343',
      email: 'mike04@gmail.com',
      autoGeneratedPassword: 'frb535y467utht'),
  Hr(
      name: 'Mike Dean',
      contact: '645875957343',
      email: 'mike04@gmail.com',
      autoGeneratedPassword: 'frb535y467utht'),
  Hr(
      name: 'Mike Dean',
      contact: '645875957343',
      email: 'mike04@gmail.com',
      autoGeneratedPassword: 'frb535y467utht'),
  Hr(
      name: 'Mike Dean',
      contact: '645875957343',
      email: 'mike04@gmail.com',
      autoGeneratedPassword: 'frb535y467utht'),
  Hr(
      name: 'Mike Dean',
      contact: '645875957343',
      email: 'mike04@gmail.com',
      autoGeneratedPassword: 'frb535y467utht'),
  Hr(
      name: 'Mike Dean',
      contact: '645875957343',
      email: 'mike04@gmail.com',
      autoGeneratedPassword: 'frb535y467utht'),
  Hr(
      name: 'Mike Dean',
      contact: '645875957343',
      email: 'mike04@gmail.com',
      autoGeneratedPassword: 'frb535y467utht'),
];
