import 'package:flutter/material.dart';
import 'package:gap/gap.dart';
import 'package:hr_app/src/models/hr.dart';

class UserAccessDialog extends StatefulWidget {
  final Hr hrMember;

  const UserAccessDialog({
    Key? key,
    required this.hrMember,
  }) : super(key: key);

  @override
  _UserAccessDialogState createState() => _UserAccessDialogState();
}

class _UserAccessDialogState extends State<UserAccessDialog> {
  late TextEditingController nameController;
  late TextEditingController contactController;
  late TextEditingController emailController;
  late TextEditingController passwordController;
  bool dashboard1 = false;
  bool staff = false;
  bool crm = false;
  bool medDelivery = false;
  bool authorization = false;
  bool report1 = false;
  bool dashboard2 = false;
  bool claimList = false;
  bool manualClaims = false;
  bool medVetting = false;
  bool refund = false;
  bool report2 = false;

  @override
  void initState() {
    super.initState();
    nameController = TextEditingController(text: widget.hrMember.name);
    contactController = TextEditingController(text: widget.hrMember.contact);
    emailController = TextEditingController(text: widget.hrMember.email);
    passwordController =
        TextEditingController(text: widget.hrMember.autoGeneratedPassword);
  }

  @override
  Widget build(BuildContext context) {
    return Dialog(
        child: SingleChildScrollView(
      child: Padding(
        padding: const EdgeInsets.all(100),
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Row(children: [
              Expanded(
                child: TextFormField(
                  controller: nameController,
                  decoration: const InputDecoration(
                      labelText: 'Name', border: OutlineInputBorder()),
                ),
              ),
              const Gap(60),
              Expanded(
                child: TextFormField(
                  controller: contactController,
                  decoration: const InputDecoration(
                      labelText: 'Contact', border: OutlineInputBorder()),
                ),
              ),
            ]),
            const Gap(60),
            Row(
              children: [
                Expanded(
                  child: TextFormField(
                    controller: emailController,
                    decoration: const InputDecoration(
                      labelText: 'Email',
                      border: OutlineInputBorder(),
                    ),
                  ),
                ),
                const Gap(20),
                Expanded(
                  child: TextFormField(
                    enabled: false,
                    controller: passwordController,
                    decoration: const InputDecoration(
                      labelText: 'Auto generated',
                      border: OutlineInputBorder(),
                    ),
                  ),
                )
              ],
            ),
            const Gap(60),
            Column(
              children: [
                Row(
                  mainAxisAlignment: MainAxisAlignment.spaceBetween,
                  children: [
                    const Expanded(
                      child: Text('Employee management'),
                    ),
                    Expanded(
                      flex: 4,
                      child: Row(
                        children: [
                          Expanded(
                            child: Column(
                              children: [
                                const Text('Employees'),
                                Checkbox(
                                  value: dashboard1,
                                  onChanged: (bool? value) {
                                    setState(() {
                                      dashboard1 = value ?? false;
                                    });
                                  },
                                ),
                              ],
                            ),
                          ),
                          const Spacer(
                            flex: 2,
                          ),
                          Expanded(
                            child: Column(
                              children: [
                                const Text('Teams management'),
                                Checkbox(
                                  value: dashboard1,
                                  onChanged: (bool? value) {
                                    setState(() {
                                      dashboard1 = value ?? false;
                                    });
                                  },
                                ),
                              ],
                            ),
                          ),
                          const Spacer(),
                        ],
                      ),
                    ),
                  ],
                ),
                Row(
                  mainAxisAlignment: MainAxisAlignment.spaceBetween,
                  children: [
                    const Expanded(
                      child: Text('Leave applications'),
                    ),
                    Expanded(
                      flex: 4,
                      child: Row(
                        children: [
                          Expanded(
                            child: Column(
                              children: [
                                const Text('Employees'),
                                Checkbox(
                                  value: dashboard1,
                                  onChanged: (bool? value) {
                                    setState(() {
                                      dashboard1 = value ?? false;
                                    });
                                  },
                                ),
                              ],
                            ),
                          ),
                          const Spacer(
                            flex: 2,
                          ),
                          Expanded(
                            child: Column(
                              children: [
                                const Text('Teams management'),
                                Checkbox(
                                  value: dashboard1,
                                  onChanged: (bool? value) {
                                    setState(() {
                                      dashboard1 = value ?? false;
                                    });
                                  },
                                ),
                              ],
                            ),
                          ),
                          const Spacer(),
                        ],
                      ),
                    ),
                  ],
                ),
                Row(
                  mainAxisAlignment: MainAxisAlignment.spaceBetween,
                  children: [
                    const Expanded(
                      child: Text('Announcements'),
                    ),
                    Expanded(
                      flex: 4,
                      child: Row(
                        children: [
                          Expanded(
                            child: Column(
                              children: [
                                const Text('Employees'),
                                Checkbox(
                                  value: dashboard1,
                                  onChanged: (bool? value) {
                                    setState(() {
                                      dashboard1 = value ?? false;
                                    });
                                  },
                                ),
                              ],
                            ),
                          ),
                          const Spacer(
                            flex: 2,
                          ),
                          Expanded(
                            child: Column(
                              children: [
                                const Text('Teams management'),
                                Checkbox(
                                  value: dashboard1,
                                  onChanged: (bool? value) {
                                    setState(() {
                                      dashboard1 = value ?? false;
                                    });
                                  },
                                ),
                              ],
                            ),
                          ),
                          const Spacer(),
                        ],
                      ),
                    ),
                  ],
                ),
                Row(
                  mainAxisAlignment: MainAxisAlignment.spaceBetween,
                  children: [
                    const Expanded(
                      child: Text('Payroll'),
                    ),
                    Expanded(
                      flex: 4,
                      child: Row(
                        children: [
                          Expanded(
                            child: Column(
                              children: [
                                const Text('Employees'),
                                Checkbox(
                                  value: dashboard1,
                                  onChanged: (bool? value) {
                                    setState(() {
                                      dashboard1 = value ?? false;
                                    });
                                  },
                                ),
                              ],
                            ),
                          ),
                          const Spacer(
                            flex: 2,
                          ),
                          Expanded(
                            child: Column(
                              children: [
                                const Text('Teams management'),
                                Checkbox(
                                  value: dashboard1,
                                  onChanged: (bool? value) {
                                    setState(() {
                                      dashboard1 = value ?? false;
                                    });
                                  },
                                ),
                              ],
                            ),
                          ),
                          const Spacer(),
                        ],
                      ),
                    ),
                  ],
                ),
                Row(
                  mainAxisAlignment: MainAxisAlignment.spaceBetween,
                  children: [
                    const Expanded(
                      child: Text('Holiday management'),
                    ),
                    Expanded(
                      flex: 4,
                      child: Row(
                        children: [
                          Expanded(
                            child: Column(
                              children: [
                                const Text('Employees'),
                                Checkbox(
                                  value: dashboard1,
                                  onChanged: (bool? value) {
                                    setState(() {
                                      dashboard1 = value ?? false;
                                    });
                                  },
                                ),
                              ],
                            ),
                          ),
                          const Spacer(
                            flex: 2,
                          ),
                          Expanded(
                            child: Column(
                              children: [
                                const Text('Teams management'),
                                Checkbox(
                                  value: dashboard1,
                                  onChanged: (bool? value) {
                                    setState(() {
                                      dashboard1 = value ?? false;
                                    });
                                  },
                                ),
                              ],
                            ),
                          ),
                          const Spacer(),
                        ],
                      ),
                    ),
                  ],
                ),
                Row(
                  mainAxisAlignment: MainAxisAlignment.spaceBetween,
                  children: [
                    const Expanded(
                      child: Text('Reporting'),
                    ),
                    Expanded(
                      flex: 4,
                      child: Row(
                        children: [
                          Expanded(
                            child: Column(
                              children: [
                                const Text('Employees'),
                                Checkbox(
                                  value: dashboard1,
                                  onChanged: (bool? value) {
                                    setState(() {
                                      dashboard1 = value ?? false;
                                    });
                                  },
                                ),
                              ],
                            ),
                          ),
                          const Spacer(
                            flex: 2,
                          ),
                          Expanded(
                            child: Column(
                              children: [
                                const Text('Teams management'),
                                Checkbox(
                                  value: dashboard1,
                                  onChanged: (bool? value) {
                                    setState(() {
                                      dashboard1 = value ?? false;
                                    });
                                  },
                                ),
                              ],
                            ),
                          ),
                          const Spacer(),
                        ],
                      ),
                    ),
                  ],
                ),
                Row(
                  mainAxisAlignment: MainAxisAlignment.spaceBetween,
                  children: [
                    const Expanded(
                      child: Text('Settings'),
                    ),
                    Expanded(
                      flex: 4,
                      child: Row(
                        children: [
                          Expanded(
                            child: Column(
                              children: [
                                const Text('User setup'),
                                Checkbox(
                                  value: dashboard1,
                                  onChanged: (bool? value) {
                                    setState(() {
                                      dashboard1 = value ?? false;
                                    });
                                  },
                                ),
                              ],
                            ),
                          ),
                          Expanded(
                            child: Column(
                              children: [
                                const Text('Employee setup'),
                                Checkbox(
                                  value: dashboard1,
                                  onChanged: (bool? value) {
                                    setState(() {
                                      dashboard1 = value ?? false;
                                    });
                                  },
                                ),
                              ],
                            ),
                          ),
                          Expanded(
                            child: Column(
                              children: [
                                const Text('Payroll setup'),
                                Checkbox(
                                  value: dashboard1,
                                  onChanged: (bool? value) {
                                    setState(() {
                                      dashboard1 = value ?? false;
                                    });
                                  },
                                ),
                              ],
                            ),
                          ),
                          Expanded(
                            child: Column(
                              children: [
                                const Text('Leave setup'),
                                Checkbox(
                                  value: dashboard1,
                                  onChanged: (bool? value) {
                                    setState(() {
                                      dashboard1 = value ?? false;
                                    });
                                  },
                                ),
                              ],
                            ),
                          ),
                          Expanded(
                            child: Column(
                              children: [
                                const Text('Attendance setup'),
                                Checkbox(
                                  value: dashboard1,
                                  onChanged: (bool? value) {
                                    setState(() {
                                      dashboard1 = value ?? false;
                                    });
                                  },
                                ),
                              ],
                            ),
                          ),
                        ],
                      ),
                    ),
                  ],
                ),
              ],
            ),
            Column(
              children: [
                ElevatedButton(
                  onPressed: () {
                    widget.hrMember.name = nameController.text;
                    widget.hrMember.contact = contactController.text;
                    widget.hrMember.email = emailController.text;
                    widget.hrMember.autoGeneratedPassword =
                        passwordController.text;
                    Navigator.pop(context);
                  },
                  child: const Text('Save'),
                )
              ],
            ),
          ],
        ),
      ),
    ));
  }
}
